site_name: Baobao Backend Documentation

python:
   version: 2 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math)
markdown_extensions:
#    - mdx_math:
#        enable_dollar_delimiter: True #for use of inline $..$
#    - fenced_code
    - codehilite
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

pages:
- Home: 'index.md'
- API Reference:
    - API文档说明: 'Reference/comments.md'
    - 用户系统:
        - 用户注册: 'Reference/user-system/login.md'
        - 获取用户信息: 'Reference/user-system/obtain.md'
        - 获取二维码信息: 'Reference/user-system/qrinfo.md'
        - 用户认证: 'Reference/user-system/validate.md'

    - 钱包系统:
        - 宝宝金余额: 'Reference/wallet-system/balance.md'
        - 宝宝金交易: 'Reference/wallet-system/transaction.md'

    - 订单系统（我的投递）:
        - version 2:
            - 订单相关接口: 'Reference/order-system/v2/order.md'
            - 记账相关接口: 'Reference/order-system/v2/bookkeeping.md'
        - 获取我的投递: 'Reference/order-system/obtain.md'
        - 用户收货地址: 'Reference/order-system/delivery_info.md'
        - 种类价格列表: 'Reference/order-system/category.md'
        - 一键下单: 'Reference/order-system/one_click_order.md'
        - 获取客户未完成订单: 'Reference/order-system/uncompleted.md'
        - 取消订单: 'Reference/order-system/cancel-order.md'
        - 评价订单: 'Reference/order-system/rate.md'

    - 商户系统:
        - version 2:
            - 装车单相关接口: 'Reference/business-system/v2/loading.md'
            - 回收站相关接口: 'Reference/business-system/v2/recycle_bin.md'
        - 获取附近回收站: 'Reference/business-system/recycle_bin.md'

    - 品类系统:
        - version 2:
            - 品类-种类: 'Reference/category/category.md'
            - 单位: 'Reference/category/unit.md'
    # - 质检系统:
    # - 站长系统:
    - 配置系统:
        - 配置系统简介: 'Reference/config-system/introduction.md'
        - 一键下单有关配置: 'Reference/config-system/client-order.md'
    #- 界面系统:
    #- 后台系统:
    - 活动:
        - 一对多分享: 'Reference/events/share1vn/referrer.md'
- Model:
    - 模型文档说明: 'Model/comments.md'
    - 钱包模型: 'Model/wallet/wallet-model.md'
    - 订单模型: 'Model/order/order-model.md'
    - 回收站模型: 'Model/business/recycle_bin-model.md'
    - 用户模型:
        - 用户收货地址模型: 'Model/user/delivery_model.md'
- View:
    - 品类系统视图:
        - 品类-种类视图: 'View/category/category.md'
        - 单位视图: 'View/category/unit.md'
    - 订单系统视图:
        - 订单视图: 'View/order/order.md'
        - 聚合视图: 'View/order/aggregate.md'
